
// Copyright 2016 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../content/public/common/result_codes.h

package org.chromium.content_public.common;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

public class ResultCode {
  @IntDef({
      NORMAL_EXIT, KILLED, HUNG, KILLED_BAD_MESSAGE, LAST_CODE
  })
  @Retention(RetentionPolicy.SOURCE)
  public @interface ResultCodeEnum {}
  public static final int NORMAL_EXIT = 0;
  public static final int KILLED = 1;
  public static final int HUNG = 2;
  public static final int KILLED_BAD_MESSAGE = 3;
  public static final int LAST_CODE = 4;
}
