
// Copyright 2016 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../content/public/common/speech_recognition_error.h

package org.chromium.content_public.common;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

public class SpeechRecognitionErrorCode {
  @IntDef({
      NONE, NO_SPEECH, ABORTED, AUDIO_CAPTURE, NETWORK, NOT_ALLOWED, SERVICE_NOT_ALLOWED,
      BAD_GRAMMAR, LANGUAGE_NOT_SUPPORTED, NO_MATCH, LAST
  })
  @Retention(RetentionPolicy.SOURCE)
  public @interface SpeechRecognitionErrorCodeEnum {}
  public static final int NONE = 0;
  public static final int NO_SPEECH = 1;
  public static final int ABORTED = 2;
  public static final int AUDIO_CAPTURE = 3;
  public static final int NETWORK = 4;
  public static final int NOT_ALLOWED = 5;
  public static final int SERVICE_NOT_ALLOWED = 6;
  public static final int BAD_GRAMMAR = 7;
  public static final int LANGUAGE_NOT_SUPPORTED = 8;
  public static final int NO_MATCH = 9;
  public static final int LAST = 9;
}
