
// Copyright 2016 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../content/public/common/top_controls_state.h

package org.chromium.content_public.common;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

public class TopControlsState {
  @IntDef({
      SHOWN, HIDDEN, BOTH, LAST
  })
  @Retention(RetentionPolicy.SOURCE)
  public @interface TopControlsStateEnum {}
  public static final int SHOWN = 1;
  public static final int HIDDEN = 2;
  public static final int BOTH = 3;
  public static final int LAST = BOTH;
}
