
// Copyright 2016 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../ui/base/window_open_disposition.h

package org.chromium.ui;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

public class WindowOpenDisposition {
  @IntDef({
      UNKNOWN, CURRENT_TAB, SINGLETON_TAB, NEW_FOREGROUND_TAB, NEW_BACKGROUND_TAB, NEW_POPUP,
      NEW_WINDOW, SAVE_TO_DISK, OFF_THE_RECORD, IGNORE_ACTION, WINDOW_OPEN_DISPOSITION_LAST
  })
  @Retention(RetentionPolicy.SOURCE)
  public @interface WindowOpenDispositionEnum {}
  public static final int UNKNOWN = 0;
  public static final int CURRENT_TAB = 1;
  /**
   * Indicates that only one tab with the url should exist in the same window.
   */
  public static final int SINGLETON_TAB = 2;
  public static final int NEW_FOREGROUND_TAB = 3;
  public static final int NEW_BACKGROUND_TAB = 4;
  public static final int NEW_POPUP = 5;
  public static final int NEW_WINDOW = 6;
  public static final int SAVE_TO_DISK = 7;
  public static final int OFF_THE_RECORD = 8;
  public static final int IGNORE_ACTION = 9;
  /**
   * Update when adding a new disposition.
   */
  public static final int WINDOW_OPEN_DISPOSITION_LAST = 9;
}
