
// Copyright 2016 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../base/android/library_loader/library_load_from_apk_status_codes.h

package org.chromium.base.library_loader;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

public class LibraryLoadFromApkStatusCodes {
  @IntDef({
      UNKNOWN, NOT_SUPPORTED_OBSOLETE, SUPPORTED_OBSOLETE, SUCCESSFUL, USED_UNPACK_LIBRARY_FALLBACK,
      USED_NO_MAP_EXEC_SUPPORT_FALLBACK_OBSOLETE, MAX
  })
  @Retention(RetentionPolicy.SOURCE)
  public @interface LibraryLoadFromApkStatusCodesEnum {}
  public static final int UNKNOWN = 0;
  public static final int NOT_SUPPORTED_OBSOLETE = 1;
  public static final int SUPPORTED_OBSOLETE = 2;
  public static final int SUCCESSFUL = 3;
  public static final int USED_UNPACK_LIBRARY_FALLBACK = 4;
  public static final int USED_NO_MAP_EXEC_SUPPORT_FALLBACK_OBSOLETE = 5;
  public static final int MAX = 6;
}
