
// Copyright 2016 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../base/memory/memory_pressure_listener.h

package org.chromium.base;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

public class MemoryPressureLevel {
  @IntDef({
      NONE, MODERATE, CRITICAL
  })
  @Retention(RetentionPolicy.SOURCE)
  public @interface MemoryPressureLevelEnum {}
  public static final int NONE = 0;
  public static final int MODERATE = 1;
  public static final int CRITICAL = 2;
}
